title: Eric Grandt
markdown: kramdown

url: https://ericgrandt.com
permalink: /blog/:categories/:year/:month/:day/:title/

pagination:
  enabled: true
  per_page: 10

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2