title: Eric Grandt
markdown: kramdown

url: https://ericgrandt.com
permalink: /blog/:categories/:year/:month/:day/:title/

paginate: 5
paginate_path: /blog/page:num/

plugins:
  - jekyll-seo-tag
  - jekyll-paginate